### ISSUE TITLE
Crash when using water walk spell

### ISSUE THREAD

**Issue by Kraintrain** [WinDanesz/AncientSpellcraft#10]
Here's the crash log:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/16/21 6:10 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 4
	at com.windanesz.ancientspellcraft.handler.MetamagicHandler.setCooldown(MetamagicHandler.java:170)
	at com.windanesz.ancientspellcraft.handler.MetamagicHandler.onMetaMagicFinished(MetamagicHandler.java:141)
	at com.windanesz.ancientspellcraft.handler.MetamagicHandler.onSpellCastPreEvent(MetamagicHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_237_MetamagicHandler_onSpellCastPreEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at electroblob.wizardry.item.ItemWand.canCast(ItemWand.java:453)
	at electroblob.wizardry.item.ItemWand.func_77659_a(ItemWand.java:377)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.windanesz.ancientspellcraft.handler.MetamagicHandler.setCooldown(MetamagicHandler.java:170)
	at com.windanesz.ancientspellcraft.handler.MetamagicHandler.onMetaMagicFinished(MetamagicHandler.java:141)
	at com.windanesz.ancientspellcraft.handler.MetamagicHandler.onSpellCastPreEvent(MetamagicHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_237_MetamagicHandler_onSpellCastPreEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at electroblob.wizardry.item.ItemWand.canCast(ItemWand.java:453)
	at electroblob.wizardry.item.ItemWand.func_77659_a(ItemWand.java:377)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Krain_Train'/312, l='MpServer', x=94.97, y=63.00, z=124.55]]
	Chunk stats: MultiplayerChunkCache: 1672, 1672
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (128,64,148), Chunk: (at 0,4,4 in 8,9; contains blocks 128,0,144 to 143,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 41798 game time, 41798 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 115 total; [EntityWitch['Witch'/10, l='MpServer', x=31.53, y=13.00, z=107.53], EntityBat['Bat'/11, l='MpServer', x=33.91, y=13.09, z=103.42], EntitySkeleton['Skeleton'/12, l='MpServer', x=28.49, y=21.00, z=117.27], EntityBat['Bat'/13, l='MpServer', x=33.05, y=17.97, z=113.60], EntityZombie['Zombie'/18, l='MpServer', x=32.50, y=14.00, z=98.18], EntityCreeper['Creeper'/19, l='MpServer', x=44.50, y=17.00, z=104.50], EntityCreeper['Creeper'/20, l='MpServer', x=38.50, y=18.00, z=119.50], EntityBat['Bat'/22, l='MpServer', x=47.71, y=25.23, z=200.09], EntityCreeper['Creeper'/29, l='MpServer', x=50.26, y=64.00, z=46.74], EntityDorpa['Infected Big Spider'/31, l='MpServer', x=56.78, y=16.00, z=77.22], EntitySquid['Squid'/32, l='MpServer', x=54.69, y=60.35, z=66.61], EntitySkeleton['Skeleton'/33, l='MpServer', x=49.50, y=46.00, z=129.50], EntitySquid['Squid'/34, l='MpServer', x=57.60, y=61.16, z=152.65], EntitySquid['Squid'/35, l='MpServer', x=50.91, y=57.67, z=174.70], EntityCreeper['Creeper'/36, l='MpServer', x=52.51, y=40.00, z=181.82], EntityBat['Bat'/37, l='MpServer', x=41.38, y=23.67, z=206.22], EntityBat['Bat'/40, l='MpServer', x=74.75, y=25.10, z=79.47], EntityItem['item.item.string'/41, l='MpServer', x=75.04, y=63.00, z=91.95], EntityItem['item.item.arrow'/42, l='MpServer', x=65.09, y=62.00, z=84.52], EntityItem['item.item.bone'/43, l='MpServer', x=64.42, y=62.00, z=82.80], EntityHull['Primitive Manducater'/44, l='MpServer', x=77.62, y=63.00, z=104.33], EntityBat['Bat'/45, l='MpServer', x=92.31, y=50.11, z=114.20], EntitySquid['Squid'/46, l='MpServer', x=80.45, y=59.05, z=148.67], EntitySquid['Squid'/47, l='MpServer', x=64.67, y=60.72, z=144.83], EntitySkeleton['Skeleton'/48, l='MpServer', x=76.50, y=45.00, z=184.50], EntityPig['Pig'/49, l='MpServer', x=65.75, y=70.00, z=203.50], EntityZombie['Zombie'/50, l='MpServer', x=79.38, y=64.00, z=204.10], EntityPig['Pig'/61, l='MpServer', x=100.21, y=63.00, z=90.45], EntityBano['Primitive Bolster'/62, l='MpServer', x=82.38, y=63.00, z=102.81], EntityItem['item.item.bone'/63, l='MpServer', x=95.76, y=47.00, z=113.67], EntityItem['item.item.rottenFlesh'/64, l='MpServer', x=80.72, y=49.00, z=120.49], EntityItem['item.item.rottenFlesh'/65, l='MpServer', x=80.89, y=49.00, z=122.87], EntityBat['Bat'/66, l='MpServer', x=94.32, y=47.06, z=114.67], EntityBat['Bat'/67, l='MpServer', x=88.07, y=26.10, z=143.38], EntityMudo['Rupter'/68, l='MpServer', x=73.38, y=25.00, z=150.95], EntityItem['item.item.arrow'/69, l='MpServer', x=92.28, y=31.00, z=142.79], EntitySquid['Squid'/70, l='MpServer', x=90.05, y=56.84, z=147.07], EntityItem['item.item.string'/71, l='MpServer', x=93.54, y=24.00, z=144.97], EntityBat['Bat'/72, l='MpServer', x=76.75, y=24.10, z=152.25], EntityNogla['Primitive Reeker'/74, l='MpServer', x=88.52, y=37.00, z=144.36], EntitySkeleton['Skeleton'/75, l='MpServer', x=81.50, y=18.00, z=185.50], EntityCreeper['Creeper'/76, l='MpServer', x=81.50, y=68.00, z=191.50], EntityZombie['Zombie'/78, l='MpServer', x=80.51, y=65.00, z=206.26], EntitySilencingSigil['entity.ancientspellcraft:silencing_sigil.name'/80, l='MpServer', x=80.94, y=71.00, z=236.58], EntityCreeper['Creeper'/81, l='MpServer', x=110.50, y=68.00, z=70.50], EntityCreeper['Creeper'/82, l='MpServer', x=111.50, y=68.00, z=72.50], EntitySkeleton['Skeleton'/83, l='MpServer', x=108.46, y=68.00, z=76.68], EntityPig['Pig'/84, l='MpServer', x=111.85, y=64.00, z=114.38], EntityItem['item.item.bone'/85, l='MpServer', x=96.05, y=48.00, z=110.13], EntityItem['item.item.arrow'/86, l='MpServer', x=96.27, y=47.00, z=113.13], EntityMudo['Rupter'/87, l='MpServer', x=111.89, y=51.00, z=122.31], EntityMudo['Rupter'/88, l='MpServer', x=115.57, y=55.00, z=119.12], EntityItem['item.item.sulphur'/89, l='MpServer', x=98.76, y=63.00, z=120.65], EntityItem['item.item.rottenFlesh'/90, l='MpServer', x=111.64, y=31.00, z=165.85], EntityItem['item.item.rottenFlesh'/91, l='MpServer', x=104.86, y=31.00, z=161.36], EntityItem['item.item.rottenFlesh'/92, l='MpServer', x=106.23, y=31.00, z=160.09], EntityItem['item.item.rottenFlesh'/93, l='MpServer', x=106.39, y=31.00, z=162.04], EntityMudo['Rupter'/94, l='MpServer', x=103.54, y=43.00, z=169.57], EntityMudo['Rupter'/95, l='MpServer', x=101.76, y=43.00, z=167.50], EntityItem['item.item.arrow'/96, l='MpServer', x=102.89, y=43.00, z=168.87], EntityItem['item.item.bone'/97, l='MpServer', x=102.23, y=43.00, z=169.78], EntityItem['item.item.rottenFlesh'/105, l='MpServer', x=122.93, y=64.00, z=62.57], EntityTippedArrow['Arrow'/106, l='MpServer', x=121.17, y=65.04, z=62.28], EntityItem['item.item.arrow'/107, l='MpServer', x=120.22, y=65.00, z=62.92], EntityItem['item.item.bone'/108, l='MpServer', x=122.13, y=65.00, z=64.83], EntityPig['Pig'/109, l='MpServer', x=125.49, y=67.00, z=104.25], EntityPig['Pig'/110, l='MpServer', x=122.79, y=68.00, z=96.22], EntitySkeleton['Skeleton'/111, l='MpServer', x=114.32, y=64.00, z=109.87], EntityInfHuman['Infected Human'/112, l='MpServer', x=114.25, y=52.00, z=122.43], EntityInfHuman['Infected Human'/113, l='MpServer', x=127.21, y=31.00, z=160.45], EntityInfHuman['Infected Human'/114, l='MpServer', x=117.87, y=33.00, z=159.49], EntityEmana['Primitive Yelloweye'/115, l='MpServer', x=119.80, y=43.50, z=153.20], EntityItem['item.item.rottenFlesh'/116, l='MpServer', x=123.64, y=40.00, z=175.57], EntityItem['item.item.rottenFlesh'/117, l='MpServer', x=127.42, y=33.00, z=170.24], EntityCreeper['Creeper'/118, l='MpServer', x=127.50, y=46.00, z=173.50], EntityItem['item.item.string'/119, l='MpServer', x=122.83, y=29.00, z=178.87], EntitySkeleton['Skeleton'/120, l='MpServer', x=116.46, y=27.00, z=190.23], EntityItem['item.item.srparasites.infected_flesh'/121, l='MpServer', x=124.57, y=40.00, z=180.91], EntityItem['item.item.rottenFlesh'/122, l='MpServer', x=125.88, y=40.00, z=184.17], EntityBat['Bat'/123, l='MpServer', x=131.54, y=38.89, z=168.75], EntityTippedArrow['Arrow'/130, l='MpServer', x=131.56, y=75.04, z=71.47], EntityMudo['Rupter'/131, l='MpServer', x=131.43, y=66.00, z=66.02], EntityInfHuman['Infected Human'/132, l='MpServer', x=128.37, y=64.00, z=65.07], EntityInfHuman['Infected Human'/133, l='MpServer', x=128.78, y=65.00, z=66.50], EntityItem['item.item.arrow'/134, l='MpServer', x=138.98, y=66.00, z=83.22], EntityItem['item.item.bone'/135, l='MpServer', x=139.91, y=73.00, z=83.96], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/136, l='MpServer', x=139.71, y=66.00, z=98.10], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/137, l='MpServer', x=139.12, y=66.00, z=97.97], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/138, l='MpServer', x=138.71, y=66.00, z=97.72], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/139, l='MpServer', x=138.75, y=66.00, z=97.66], EntityZombie['Zombie'/140, l='MpServer', x=133.50, y=34.00, z=114.50], EntityMudo['Rupter'/141, l='MpServer', x=136.28, y=33.00, z=138.51], EntityCreeper['Creeper'/143, l='MpServer', x=129.84, y=66.00, z=121.62], EntitySkeleton['Skeleton'/144, l='MpServer', x=137.44, y=33.00, z=138.20], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/146, l='MpServer', x=135.16, y=66.00, z=139.94], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/147, l='MpServer', x=135.15, y=66.00, z=139.88], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/148, l='MpServer', x=135.66, y=66.00, z=140.14], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/149, l='MpServer', x=134.84, y=66.00, z=139.93], EntityItem['item.item.ancientspellcraft:ancient_spell_book'/150, l='MpServer', x=135.72, y=66.00, z=139.99], EntitySkeleton['Skeleton'/151, l='MpServer', x=136.57, y=42.00, z=153.85], EntitySkeleton['Skeleton'/152, l='MpServer', x=137.47, y=44.00, z=150.72], EntityItem['item.item.arrow'/153, l='MpServer', x=138.01, y=32.00, z=166.93], EntityItem['item.item.bone'/154, l='MpServer', x=139.03, y=32.00, z=165.21], EntityCreeper['Creeper'/163, l='MpServer', x=150.40, y=64.00, z=46.85], EntityPig['Pig'/165, l='MpServer', x=147.87, y=64.00, z=88.65], EntityPig['Pig'/166, l='MpServer', x=146.90, y=66.00, z=104.48], EntityPig['Pig'/167, l='MpServer', x=150.76, y=66.00, z=108.65], EntityPig['Pig'/168, l='MpServer', x=145.82, y=66.00, z=103.46], EntityMudo['Rupter'/169, l='MpServer', x=147.45, y=67.00, z=135.40], EntityZombie['Zombie'/170, l='MpServer', x=147.50, y=50.00, z=158.50], EntityBat['Bat'/688, l='MpServer', x=59.39, y=12.09, z=70.40], EntityBat['Bat'/689, l='MpServer', x=61.64, y=12.02, z=70.04], EntityItem['item.item.bone'/696, l='MpServer', x=138.38, y=33.00, z=125.40], EntityPig['Pig'/185, l='MpServer', x=169.33, y=68.00, z=109.49], EntityPlayerSP['Krain_Train'/312, l='MpServer', x=94.97, y=63.00, z=124.55]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4605789920 bytes (4392 MB) / 5335154688 bytes (5088 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version       | Source                                  | Signature                                |
	|:------ |:----------------- |:------------- |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2        | minecraft.jar                           | None                                     |
	| LCHIJA | mcp               | 9.42          | minecraft.jar                           | None                                     |
	| LCHIJA | FML               | 8.0.99.99     | forge-1.12.2-14.23.5.2854.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854  | forge-1.12.2-14.23.5.2854.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei               | 4.15.0.296    | jei_1.12.2-4.15.0.296.jar               | None                                     |
	| LCHIJA | ebwizardry        | 4.3.2         | ElectroblobsWizardry-4.3.2-MC1.12.2.jar | None                                     |
	| LCHIJA | ancientspellcraft | 1.1.1         | AncientSpellcraft-1.1.1.jar             | None                                     |
	| LCHIJA | guideapi          | 1.12-2.1.8-63 | Guide-API-1.12-2.1.8-63.jar             | None                                     |
	| LCHIJA | journeymap        | 1.12.2-5.7.1  | journeymap-1.12.2-5.7.1.jar             | None                                     |
	| LCHIJA | neat              | 1.4-17        | Neat+1.4-17.jar                         | None                                     |
	| LCHIJA | patchouli         | 1.0-23.6      | Patchouli-1.0-23.6.jar                  | None                                     |
	| LCHIJA | srparasites       | 1.8.2         | SRParasites-1.12.2v1.8.2.jar            | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.09' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by WinDanesz** [comment]
Hi, did you cast a metamagic spell before casting water walk and the crash happened?

**Comment by WinDanesz** [comment]
Would be also helpful to know what your player was holding, a wand I guess? What upgrades it had?
