### ISSUE TITLE
charged astral diamond

### ISSUE THREAD

**Issue by wowxiz** [WinDanesz/AncientSpellcraft#12]
which spell i need to use and the correct form to use it? i tried some by the name and description, but i couldn't.

**Comment by WinDanesz** [comment]
Hi, you need the Essence Extraction spell. It takes up a lot of mana, and you must be holding a (regular) Astral Diamond in your offhand while you continuously channel the spell at an Imbuement Altar to charge the diamond. It destroys the altar.

**Comment by wowxiz** [comment]
but i need the charged astral diamond to make the imbuement altar

**Comment by WinDanesz** [comment]
Yes, the above process results in a charged astral diamond
