### ISSUE TITLE
new update exceeds maximum id range; conflicts with trinkets and baubles + resizing potion

### ISSUE THREAD

**Issue by zanderjome** [WinDanesz/AncientSpellcraft#13]

**Comment by WinDanesz** [comment]
If you are running out of potion ids, maybe JEID https://www.curseforge.com/minecraft/mc-mods/jeid can help

**Comment by WinDanesz** [comment]
the NEID mod can also help https://www.curseforge.com/minecraft/mc-mods/notenoughids
