### ISSUE TITLE
[Bug] Condensing only affects Sage Tomes while they are in the Arcane Workbench

### ISSUE THREAD

**Issue by abilliontrillionstars** [WinDanesz/AncientSpellcraft#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I added a Wand Condensing upgrade to my Advanced (Healing) Sage Tome and it doesn't regenerate mana unless it's in the center slot of an Arcane Workbench.

The upgrades already present on the tome were one Cooldown and one Attunement upgrade.

### Expected behaviour

I expected the tome to regenerate while it's in my hand or inventory.

### Steps to reproduce

1. Join a server
2. Obtain an Advanced Sage Tome of Healing
3. Apply Cooldown, Attunement, then Condensing to the tome
4. Hold it in hand for some time
5. Let it sit in the Arcane Workbench for some time

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.12.2 - 1.5.9

### Forge version

1.12.2 - 14.23.5.2858

### Other mods

This is on the latest Dan's Medieval Magic Pack instance, on the official server.

**Comment by WinDanesz** [comment]
fixed by 0d29f59
