### ISSUE TITLE
Can't move mouse cursor in the game. 

### ISSUE THREAD

**Issue by HeroInCoffee** [WinDanesz/AncientSpellcraft#15]
Lagging, and can't move cursor when enter the world. Mod list: 
AncientSpellcraft-1.1.2
Baubles-1.12-1.5.2
ElectroblobsWizardry-4.3.4-MC1.12.2
Guide-API-1.12-2.1.8-63
Mine+and+Slash-1.12.2-1.9.7
MS+Auto-Compat+1.12.2-1.0.7
OptiFine-OptiFine-1.12.2_HD_U_G5_pre1
Overlord-1.12.2-2.4.14
Patchouli-1.0-23.6
terrariaarsenal-1.1.2
ZettaiMagic+1.3.9

**Comment by HeroInCoffee** [comment]
1.1.1 AS works without issues.

**Comment by WinDanesz** [comment]
Hey, could you try to see if you can reproduce this issue with just EBwiz + latest AS version?

**Comment by HeroInCoffee** [comment]
Yes and it works. I found out optifine with latest AS have this problem.

**Comment by WinDanesz** [comment]
Thanks, I'll try to figure out whats going on with it to provide support for optifine
