### ISSUE TITLE
Spirit Ward bug

### ISSUE THREAD

**Issue by leocqueiroz** [WinDanesz/AncientSpellcraft#16]
A friend of mine casted "Spirit Ward" to discover this spell on my private server. Doing this, the server just crashed and now everytime we try to join it, our minecraft crash as well. I discover, doing tests with this spell on the single player, that if you cast this spell nerby to any block floating around you, the map will completely crash. ~ Also, when I put devoritium doors on the floor, the minecraft crash as well

**Comment by leocqueiroz** [comment]
The console message:

StackTrace :                                                                                                  */
/*     java.lang.ClassCastException:                                                                              */
/*     net.minecraft.entity.item.EntityItem                                                                       */
/*     cannot be cast to                                                                                          */
/*     net.minecraft.entity.EntityLivingBas                                                                       */
/*                                                                                                                */
/*     com.windanesz.ancientspellcraft.entity.construct.EntitySpiritWard.func_70071_h_(EntitySpiritWard.java:132) */
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167)                     */
/*     net.minecraft.world.WorldServer.redirect$zll000$onCallEntityUpdate(WorldServer.java:4761)                  */
/*     net.minecraft.world.World.func_72866_a(World.java:1996)                                                    */
/*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                         */
/*     net.minecraft.world.World.func_72870_g(World.java:1958)                                                    */
/*     net.minecraft.world.World.func_72939_s(World.java:1762)                                                    */
/*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3931)                                        */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                      */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                         */
/*     java.lang.Thread.run(Thread.java:748)

**Comment by leocqueiroz** [comment]
[crash-2021-03-03_02.03.42-client.txt](https://github.com/WinDanesz/AncientSpellcraft/files/6073702/crash-2021-03-03_02.03.42-client.txt)

**Comment by leocqueiroz** [comment]
For anyone with the same problem: There is an *APOCALYPSE* option on forge to remove every bugged entity when starting your server. But you can't control what it'll delete on your files... So use it in a last case xD. We used to fix this bug!!! To do it:

server_file/config/forge.cfg --> Change "removeErroringEntities=false" to true, and removeErroringTileEntities=true.

I strongly recommend to disable this feature after starting the server, then restart it

**Comment by WinDanesz** [comment]
Useful workaround. I've already fixed this in dev and will be released in a oatch within a few days

**Comment by WinDanesz** [comment]
Fixed in 1.1.3
https://www.curseforge.com/minecraft/mc-mods/ancient-spellcraft/files/3238582
