### ISSUE TITLE
Placing Devoritium door crashes game

### ISSUE THREAD

**Issue by JMarshmellow** [WinDanesz/AncientSpellcraft#17]
Simply placing the Devoritium door crashes the game with just Electroblob's Wizardry and Ancient Spellcraft installed. I placed the door on a grass block while in creative, if that matters. 
[crash-2021-03-06_20.00.00-client.txt](https://github.com/WinDanesz/AncientSpellcraft/files/6096008/crash-2021-03-06_20.00.00-client.txt)

**Comment by WinDanesz** [comment]
Fixed in 1.1.3
https://www.curseforge.com/minecraft/mc-mods/ancient-spellcraft/files/3238582
