### ISSUE TITLE
[Bug] Healing/Silence Sigil cannot be removed by recasting the Sigil

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

After casting a Sigil, there are few ways to remove it. While you can set off many of the Sigils, Silence Sigil cannot be triggered.

Tried recasting Silence Sigil, but this also failed.

Dispel Magic can remove the Sigils, but the caster may not have found this spell.

### Expected behaviour

I expected a easy option to remove all sigils, such as by recasting the sigil spell with the sigil as a target.

### Steps to reproduce

1. Join a Server
2. Cast Silence Sigil
3. Attempt to remove it with a recast

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
Are other sigils removed on recast, e.g. the fire sigil? Does that require sneaking?

**Comment by KnightCa** [comment]
Other sigils do not remove on cast, but can be triggered fairly easily to remove (although it would be better to be able to recast (ie uncast) to remove them.I plan to put in a request have them removable this way as well.The biggest issue is with Silence sigil as there is no way to remove it by triggering it.On Nov 30, 2023, at 8:29 AM, WinDanesz ***@***.***> wrote:﻿
Are other sigils removed on recast, e.g. the fire sigil? Does that require sneaking?

**Comment by WinDanesz** [comment]
Workaround, but Dispel Greater/Lesser magic removes it

**Comment by KnightCa** [comment]
I did know that dispel magic works, but casters may not have discovered those spells to do so.On Nov 30, 2023, at 10:38 AM, WinDanesz ***@***.***> wrote:﻿
Workaround, but Dispel Greater/Lesser magic removes it
