### ISSUE TITLE
[Bug] Pocket Library crashes Single-player game

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Casting Pocket Library immediately crashed a Single-player game. Hesitant to use on a Server with concern about crashing it.

Tried 3 times with same results.

Notable results from Crashlog:

GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.

Description: Ticking player

java.lang.NullPointerException: Ticking player
    at com.windanesz.ancientspellcraft.spell.PocketLibrary.spawnStructureInitially(PocketLibrary.java:190)
    at com.windanesz.ancientspellcraft.spell.PocketLibrary.cast(PocketLibrary.java:137)
    at com.windanesz.ancientspellcraft.item.ItemSageTome.cast(ItemSageTome.java:438)
    at com.windanesz.ancientspellcraft.item.ItemSageTome.onUsingTick(ItemSageTome.java:354)
    at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2678)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2097)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

### Expected behaviour

I expected the Pocket Library to work in both single-player and server environments.

### Steps to reproduce

1. Start single-player
2. Equip full set of generic Sage Robes and Sage tome with Pocket Library
3. Cast Pocket Library

This happened with both the Master Fire Sage tome and the Master Healer Sage tome. Haven't tried it with others.

### Crashlog

https://gist.github.com/KnightCa/c1c2a50cc814f374e9b80ba490c88e7f

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

### Other mods

!configanytime-1.0.jar
!mixinbooter-8.9.jar
AkashicTome-1.2-12.jar
ancientbeasts-1.9.99999.jar
AncientSpellcraft-1.12.2-1.5.10.jar
antiqueatlas-1.12.2-4.6.3.jar
AppleSkin-mc1.12-1.0.14.jar
Aquaculture-1.12.2-1.6.8.jar
ArcaneApprentices-1.12.2-1.0.2.jar
arcane_essentials-1.0.1.jar
ArtemisLib-1.12.2-v1.0.6.jar
AutoRegLib-1.3-32.jar
Baubles-1.12-1.5.2.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
betterbiomeblend-1.12.2-1.1.7-forge.jar
bettercaves-1.12.2-2.0.4.jar
BetterDisplays-1.12.2-1.1.1.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
betternether-0.1.8.6.jar
BetterSpartanArchery-1.12.2-1.4.1-1.2a.jar
BetterThirdPerson-Forge-1.12.2-1.9.0.jar
BiblioCraft[v2.4.6][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
bonsaitrees-1.1.4-b170.jar
Bountiful-1.12.2-2.2.3.jar
Capsule-1.12.2-3.4.76.jar
carryon-1.12.2-1.12.7.23.jar
censoredasm5.18.jar
Chameleon-1.12-4.1.3.jar
champions-1.12.2-1.0.11.10.jar
Charm-1.12.2-1.4.1.jar
ChestTransporter-1.12.2-2.8.8.jar
ChickenChunks-1.12.2-2.4.2.74-universal.jar
ClientTweaks_1.12.2-3.1.11.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
colytra-1.12.2-1.2.0.4.jar
comforts-1.12.2-1.4.1.3.jar
Controlling-3.0.12.2.jar
coroutil-1.12.1-1.2.37.jar
CosmeticArmorReworked-1.12.2-v5a.jar
CraftingTweaks_1.12.2-8.1.9.jar
CraftTweaker2-1.12-4.1.20.695.jar
Customized-Dungeon-Loot-1.12 -(v.1.0.3).jar
Cyclic-1.12.2-1.20.14.jar
DebugServerInfo-1.12.2-1.0.5.jar
DoggyTalents-1.12.2-1.15.1.6.jar
DrZharks-MoCreatures-Extended-12.3.1.jar
DungeonTactics-1.12.2-0.16.9.jar
DynamicTrees-1.12.2-0.9.29.jar
DynamicTreesBOP-1.12.2-1.5.2.jar
DynamicTreesQuark-1.12.2-1.0.6.jar
dynamictreesTheTwilightForest-1.12.2-1.2.3.jar
easiervillagertrading-1.12-forge14.21.1.2387-1.3.jar
ElectroblobsWizardry-4.3.11.jar
ElenaiDodge-1.12.2-2.1.jar
EnchantmentDescriptions-1.12.2-1.1.20.jar
EndReborn [0.3.9].jar
EntityCulling-1.12.2-6.4.1.jar
extraalchemy-forge-1.12-build11-0.5.4.jar
ExtraGolems-1.12-7.1.9.jar
ExtraSpells-1.12.2-1.2.0.jar
eyeofdragons-0.0.2.jar
Fish's Undead Rising-1.4.0.jar
foamfix-0.10.15-1.12.2.jar
forbidden_arcanus-1.12.2-1.1.4.jar
forgeautofish-1.0.4-1.12.2.jar
Forgelin-1.8.4.jar
FTBLib-5.4.7.2.jar
FTBUtilities-5.4.1.131.jar
furniture-6.3.2-1.12.2.jar
future-mc-0.2.11.jar
geckolib-forge-1.12.2-3.0.31.jar
Ghostspells-0.7-alpha.jar
gogredux-1.12.2-1.0.0.jar
GrimoireOfGaia3-1.12.2-1.7.2.jar
HappyTrails-1.12.2-1.0.0.5.jar
HardcoreDarkness-MC1.12.2-2.0.jar
heroicarmory-1.2.0.jar
hunterillager-1.12.2-1.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
IceAndFireRotN-1.9.1-1.2.0.jar
IllagersPlus-1.12.2-1.1.3.jar
InfernalMobs-1.12.2.jar
InventoryHUD-1.12.2.forge-3.4.4.jar
InventoryTweaks-1.63.jar
ItemPhysic Lite 1.3.7 mc1.12.2.jar
jeiintegration_1.12.2-1.6.0.jar
jei_1.12.2-4.16.1.1003.jar
journeymap-1.12.2-5.7.1.jar
LegendaryTooltips-1.12.2-1.1.10.jar
llibrary-1.7.20-1.12.2.jar
Locks-1.12.2-3.0.0.jar
LootTweaker-0.3.1+MC1.12.2.jar
lycanitesmobs-1.12.2-2.0.8.9.jar
mcw-bridges-1.0.6b-mc1.12.2.jar
minerva-library-1.0.13.jar
MmmMmmMmmMmm-1.12-1.14.jar
MoBends_1.12.2-1.2.1-19.12.21.jar
moreoverlays-1.15.1-mc1.12.2.jar
MoSpells-1.12.2-1.0.4.jar
MouseTweaks-2.10-mc1.12.2.jar
movingelevators-1.4.4-forge-mc1.12.jar
mowziesmobs-1.5.8.jar
MultithreadedNoise-1.12.2-0.0.2.jar
namepain-1.5.0 forge-1.12.x.jar
NaturesCompass-1.12.2-1.8.5.jar
Neat+1.4-17.jar
Nothirium-1.12.2-0.3.4-beta.jar
OptiFine_1.12.2_HD_U_G5.jar
OreExcavation-1.4.150.jar
particleculling-1.12.2-v1.4.1.jar
Patchouli-1.0-23.6.jar
PiTweaks-1.12-1.1.1.jar
PortableCrafting-1.12.2-1.0.2.jar
PotionCore-1.9_for_1.12.2.jar
ProgressiveBosses-1.5.4-mc1.12.x.jar
Quark-r1.6-179.jar
QuarkOddities-1.12.2.jar
randompatches-1.12.2-1.22.1.10.jar
RandomThings-MC1.12.2-4.2.7.4.jar
randomtweaks-1.12.2-2.8.3.1.jar
ReachFix-1.12.2-1.0.9.jar
RenderLib-1.12.2-1.3.3.jar
Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar
RLCombat-1.12.2-2.0.8.jar
RLMixins-1.2.19.jar
RoguelikeDungeonsFnarEdition-1.12.2-2.4.4.jar
RoughlyEnoughIDs-2.0.6.jar
rustic-1.1.7.jar
shapeselector-1.12.2b4.jar
simplecore-1.12.2-1.7.3.4.jar
SimpleFlax-1.2.1.jar
simpleores-1.12.2-1.11.2.2.jar
SimpleStorageNetwork-1.12.2-1.8.3.jar
simplybackpacks-1.4.9.jar
SoManyEnchantments-0.5.5.jar
SophisticatedWolves-1.12.2-3.13.8.jar
SoundFilters-0.12.1_for_1.12.jar
spartancompat-1.2.3.jar
spartanfire-0.08.jar
SpartanShields-1.12.2-1.5.5.jar
spartantwilight-1.12.2-1.2.0.jar
SpartanWeaponry-1.12.2-1.5.3.jar
SpellBundle-1.12.2-1.1.4.jar
StorageDrawers-1.12.2-5.5.0.jar
supermartijn642configlib-1.1.8-forge-mc1.12.jar
TFSpellPack-1.1.0-MC1.12.2.jar
Tips-1.12.2-1.0.9.jar
tombstone-4.6.2-1.12.2.jar
TravelersBackpack-1.12.2-1.0.35.jar
twilightforest-1.12.2-3.11.1021-universal.jar
UniversalTweaks-1.12.2-1.8.0.jar
VanillaTweaks-1.12.2-1.5.6.jar
VillageNames-1.12.2-4.4.6.jar
villager-market-1.12.2-1.0.2.jar
WailaHarvestability-mc1.12-1.1.12.jar
Wawla-1.12.2-2.6.275.jar
Waystones_1.12.2-4.1.0.jar
WizardryFates-2.1.0.jar
WizardryGolems-1.12.2-1.2.0.jar
WizardryNecromancersDelight-1.12.2-1.0.5.jar
WizardryTales-1.4.0.jar
WizardryTales-2.2.2.jar
WizardryUtils-1.12.2-1.1.4.jar
XPOrbClump-1.2.jar
xptome-1.12.2-v2.0.1.jar
YABBA-1.1.2.54.jar
ZettaiMagic-1.4.7.jar
zombieawareness-1.12.1-1.11.16.jar
[1.12.2]DamageIndicatorsMod-3.5.1.jar
_supermartijn642corelib-1.1.15-forge-mc1.12.jar

**Comment by KnightCa** [comment]
Looked at the 141 bug report and it looks like a similar crash report (ticking player).

**Comment by KnightCa** [comment]
Attempted all normal fixes:
1. Made sure video driver was updated and that Minecraft is using graphic card
2. Tried removing Options.txt
3. Updated Java to latest version
4. Downgraded Java to version 8.51

None had any effect. This spell used to work in a older release of Ancient Spellcraft. Later, I may downgrade Ancient Spellcraft to identify the working version.

**Comment by WinDanesz** [comment]
I'm aware of this, fixed in dev already. Will close the ticket with the commit push.

**Comment by KnightCa** [comment]
Perfect, thank youOn Nov 30, 2023, at 12:46 AM, WinDanesz ***@***.***> wrote:﻿
I'm aware of this, fixed in dev already. Will close the ticket with the commit push.
