### ISSUE TITLE
Unable to Craft Spells using the Scribing table when all 3 components are not uses

### ISSUE THREAD

**Issue by SteamDoge9000** [WinDanesz/AncientSpellcraft#19]
![image](https://user-images.githubusercontent.com/38770780/110259334-20048380-7f75-11eb-8bf3-37121165a8f0.png)

it works for making spells where all 3 slots are used but for some reason it dosent work for ones that dont use all the slots

am I doing something wrong or is this some sort of bug on the mods end?

**Comment by WinDanesz** [comment]
Fixed in 1.1.3
https://www.curseforge.com/minecraft/mc-mods/ancient-spellcraft/files
