### ISSUE TITLE
[Bug] Chant of Celerity shows up as both a ebwizardry book icon and ancient spellcraft icon

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When looking at the book cover and format for the Chant of Celerity, it has two versions..
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/310e971d-469f-4e46-bb9a-4c2d60e92a35)

One version shows up as a Ancient Spellcraft book and format (likely correct)
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/53d30f57-b604-4e39-bf35-534fc9433e90)
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/4f152336-2a7d-4650-86ec-ec9c2c4dac52)

And the other shows up as a ebwizardry book and format (likely incorrect)
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/97d42edd-85d2-40ec-b771-28dd230f882a)
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/dc16c7b6-b1b1-46da-9f07-5a332cd50f28)

### Expected behaviour

I would expect that Chant of Celerity would appear like the other Ancient spellcraft icons and book format.

Please remove the ebwizardry version.

### Steps to reproduce

1. Join a Server
2. Look at the two versions of Chant of Celerity found in JEI
3. Check the format of the books after you right click them on the hot bar.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
Must be specific to your pack. Try it on a new world

**Comment by KnightCa** [comment]
Yep, was due to having the old spellbook before the mod update.
