### ISSUE TITLE
What does the Evergrowing Crystal do?

### ISSUE THREAD

**Issue by Sharpeims** [WinDanesz/AncientSpellcraft#20]
What does the Evergrowing Crystal artifact do?

**Comment by WinDanesz** [comment]
It can be right clicked each day to get some random crystals. What do you see in the item tooltips?

**Comment by Sharpeims** [comment]
These magical crystals are constantly growing by accumulating ambient magic

**Comment by Sharpeims** [comment]
Ty tho, I was wondering what it did for ages

**Comment by WinDanesz** [comment]
It didn't say the right click usage? The tooltip should have that in the next line. If its missing then its a bug which needs to be fixed
