### ISSUE TITLE
[Bug] Contingency - Immobilization does not help against spiderweb or other movement hindering effects

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When movement is reduced by quicksand, spiderwebs, Cobweb spell, then the Contingency - Immobilization spell does not activate.

Contingency - Immobilization works correctly against the Frostbite spell and the Paralysis spell

### Expected behaviour

I expected the Contingency - Immobilization to be more widely useable (ie activate) in situation where the character is almost immobilized. These would include being stuck in quicksand or getting caught in spiderwebs (either from the Cobweb spell or naturally occurring in areas).

### Steps to reproduce

1. Join a Server
2. Cast Contingency - Immobilization, followed by a Healing spell
3. Make sure not to be at full health
4. Put yourself in quicksand or spiderwebs
5. Notice that even with drastically reduced speed, Contingency - Immobilization does not activate

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by KnightCa** [comment]
@WinDanesz This worked great. Any chance we can add biomesoplenty:quicksand to the triggers for this effect.

It works great with Quicksand created by spells as well as all types of webbing (spell, natural, Grimoire of Gaia, Lycanite, etc)

**Comment by WinDanesz** [comment]
Sure
