### ISSUE TITLE
[Bug] Words of Unbinding randomly removes upgrade while holding a off-hand upgrade scroll

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

While casting Words of Unbinding while holding the Sage Tome Sentience Upgrade in the off-hand, a random upgrade is removed (in this case it was a Attunement upgrade removed).

In addition, if a Attunement upgrade is removed, the Sage Tome continues to have the same number of spells listed in it until a Attunement upgrade is re-applied to it.

If you then add a Attunement upgrade back to the Sage Tome, it fails to use up the Attunement upgrade scroll.

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/6b1c0ffb-ea51-4e4f-8cc4-454353bab6a9)

### Expected behaviour

According to the github "Removes a random wand upgrade from the wand which casts this spell. You can control which upgrade is being removed if you hold the upgrade's scroll in your offhand."

I expected Words of Unbinding to remove the offhand upgrade from the Sage Tome.

If a Attunement upgrade is removed, I expected the number of assigned spells to be reduced as well.

### Steps to reproduce

1. Join a Server
2. Add the following Wand Upgrades: 3 Attunement, 2 Sage Tome Sentience, 2 Blast
3. While holding a Sage Tome Sentience upgrade scroll in offhand, cast Words of Unbinding
4. Notice which Upgrade is removed

It's random which upgrade is removes, so repeat to see the randomness if necessary.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
> If a Attunement upgrade is removed, I expected the number of assigned spells to be reduced as well.


fixed by  15e7ba6201da57aa7ee75b0139da2002ae3a6fc0
