### ISSUE TITLE
[Bug] Anti-magic Field has a counter that does not accurately track the duration (alternates 1 or 2 seconds the entire time)

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

After casting Anti-magic Field, a counter appears that rapidly alternates the entire duration between 1 or 2 seconds remaining. It does not accurately track the remaining duration.

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/772fe5d3-7b3c-4e25-9f1d-92b844fdada9)

### Expected behaviour

I expect that casting Anti-magic Field results in a accurate duration remaining counter.

### Steps to reproduce

1. Join the Server
2. Cast Anti-magic Field
3. Note the incorrect duration counter on the screen

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
There is no way to track this duration in other way. If the area effect lasts for N seconds, and I make it to apply the potion effect for N seconds, then even if you leave the area, you'll still have the effect. This way it will only linger for 1-2 seconds
