### ISSUE TITLE
[Bug] Forced Channel appears to have no effect when used on a NPC Wizard/Sage/Warlock/Battlemage mob

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Casting Forced Channel appears to have no effect when used on a NPC Wizard/Sage/Warlock/Battlemage mob.

### Expected behaviour

I expected casting Forced Channel while targeting a Wizard/Sage/Warlock/Battlemage mob would either give the caster a Buff (if the spell the mob is currently set to is a healing spell or such) or cast a offensive spell at the mob (if the mob is set to a offensive spell).

### Steps to reproduce

1. Join a Server
2. Cast Forced Channel on a Wizard/Sage/Warlock/Battlemage mob
3. Note the lack of any effect

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
For each unique wizard entity, the spell always select one specific spell from the wizard's known spells. It works for most spells, might not work for all.
