### ISSUE TITLE
[Bug] Cure Zombie fails to turn targeted Zombie Villager into Villager

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Casting Cure Zombie on a Zombie Villager fails to turn it into a Villager

### Expected behaviour

I expected a Zombie Villager to turn back into a Villager after being targeted by Cure Zombie

### Steps to reproduce

1. Join a Server
2. Target a Zombie Villager with Cure Zombie
3. Notice lack of effect

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.10

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
The effect is not immediate, works the same way as vanilla. Zombies shake and eventually transform back
