### ISSUE TITLE
[Bug] Animate Weapon with a Wand does not work with all Novice/Apprentice Projectile/Attack/Minion spells

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Casting Animate Weapon on a Wand animates the wand, and will generally cast Novice or Apprentice level spells that are Projectile, Attack, or Minion type.

However, certain spells that fit into these categories cause the wand to just float in place and fail to attack.

Apprentice (Projectile) Spells:
Explosion

Apprentice (Attack) Spells:
Pyrokinesis
Solar Beam

Apprentice (Minion) Spells:
Conjure Lesser Sentry = Should be Minion type, but is currently set to Utility type
Summon Spirit Wolf
Summon Snow Golem

### Expected behaviour

I expected the Wand to be able to cast all Novice or Apprentice level spells that have the Projectile, Attack, or Minion type.

### Steps to reproduce

1. Join a Server
2. Cast Animate Weapon to animate a Wand that has the Solar Beam spell (or another on the list)
3. Notice it fails to attack nearby mobs with the spell.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
What spells did your wand have?

**Comment by KnightCa** [comment]
From thorough testing, it appears that the Animate Weapon spell when used on a Wand is supposed to work with Novice to Apprentice level spells with either the Projectile, Attack, or Minion type.

Using Master Wand with a single spell assigned at a time, these were the results:

All Novice (Projectile/Attack/Minion) Spells succeed.

Apprentice (Projectile) Spells succeed:
Death Page
Druid Hex
Fireball
Firebolt
Firebomb
Flint Shard
Frizzle
Frost Bomb
Homing Spark
Iceball
Ice Shard
Lightning Arrow
Poison Ball
Poison Bomb
Precise Magic Missile
Spark Bomb
Sploosh
Stink Bomb
Twilight Orb
Water Arrow

Apprentice (Projectile) Spells **fail**:
Explosion (Zettai Magic spell, set as NPC=false.. thus not useable by minion Wand)

Apprentice (Attack) Spells succeed:
Banish
Bubble
Burning Disease
Cyclone Bolt
Darkness Hand
Entangle
Flame Ray
Frost Blast
Frost Breath
Frost Ray
Ice Statue
Ignition
Life Drain
Lightning Ray
Molten Earth
Ocean Burst
Poison
Quake
Seal of Confusion
Seal of Dread
Shock Zone
Wind Slash
Winds of Winter
Wither
Zammle

Apprentice (Attack) Spells **fail**:
Pyrokinesis (Ancient Spellcraft spell, changed to NPC=true.. thus useable by minion Wand)
Solar Beam (Mo spell, set as NPC=false.. thus not useable by minion Wand)

Apprentice (Minion) Spells succeed:
Conjure Mycosis
Conjure Wraith
Summon Ember
Summon Ghost
Summon Goblin
Summon Skeleton
Summon Skeleton Druid
Summon Sword Skeleton

Apprentice (Minion) Spells **fail**:
Summon Spirit Wolf (EB Wizardry spell, player-specific, set as NPC=false.. thus not useable by minion Wand)
Summon Snow Golem (EB Wizardry spell, set as NPC=false.. thus not useable by minion Wand)

Advanced/Master Spells fail

**Comment by WinDanesz** [comment]
I fixed Pyrokinesis, now NPCs will cast it. None of these spells are Animate-specific, but NPC specific, hence most won't be fixed.
Explosion - did you mean Detonate? I'm not familiar with is
Pyrokinesis - fixed
Solar Beam - probably won't be fixed, its a bit hacky spell
Conjure Lesser Sentry - Technially these are not really minions but blocks, NPCs cant cast it
Summon Spirit Wolf - player specific, won't be fixed
Summon Snow Golem - EbWiz makes these uncastable for NPCs, should be raised for that mod. Should be discussed in the ebwiz server whether we want wizards to cast it

Key takeaway, the base mod and spell pack spells are controlling this via code and the spell property jsons, if a spell is NPC-castable, it should work with Animated Wands. So I can't fix it from my side, other than my own pack spells or the base mod spells maybe.

**Comment by WinDanesz** [comment]
Still, I appreciate your thorough testing!

**Comment by KnightCa** [comment]
Thank you very much. Thorough answer and that makes complete sense.

**Comment by KnightCa** [comment]
@WinDanesz Would it be possible to update the description for Animate Weapon to:

"Animate off-hand weapon to fight for you in battle. The effect ends after 30 seconds or if it is killed. 

A animated wand can cast Novice or Apprentice spells of the Projectile, Attack, or Minion type useable by NPC Wizards."
