### ISSUE TITLE
[Bug] Forcefend is too limited as a Advanced spell

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When trying to use Forcefend to redirect two Skeletons arrows, it was too difficult to time the spell for just when the arrows are in flight.

In addition, even the deflected arrows did not redirect to hit the other skeleton.

### Expected behaviour

I expected Forcefend to have a duration countdown (or be a Continous spell), during which it would redirect projectiles (both magical and mundane [such as arrows, crossbow bolts, javelins, spears, darts, throwing knives]) at the other mob.

If having a duration makes it too strong, consider lessoning the duration each time it redirects a projectile.

### Steps to reproduce

1. Join a Server
2. Setup a fight with you and 2 Skeleton Archers
3. Cast Forcefend non-stop in a attempt to redirect the incoming arrows
4. Notice the lack of success

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
forcefend is a continuous channel spell, not something that needs timing

**Comment by KnightCa** [comment]
Gotcha, closing this then
