### ISSUE TITLE
[Bug] Battlemage Forts sometimes have displaced dirt layer under them or cut off walls of Ancient Vaults

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Occasionally a Battlemage Fort will spawn with a odd large dirt patch near them (rotational calculation bug, flat earth is supposed to be under the fort):

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/1d72c60b-614d-4b26-a60a-2474a9cd9021)

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/a8a69a8a-eb26-4ff1-9ae0-3a88fce43255)

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/7ce410f3-32cd-42d8-b8e5-a9b3bf16d6cb)

Structures that spawn too close together end up forcing one Structure to be missing part of its outer wall:

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/df716a49-04af-43d0-b544-a3fac6fe9995)

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/bd9c2aea-d3bf-4b07-87ca-e24c8c2e2388)

### Expected behaviour

I expected a Battlemage Fort to have the dirt/sand under the Fort rather than to the side.

I also expected Ancient Spellcraft Structures to not be able to displace part of other Structures (perhaps a config that sets how apart they can be found from one another)?

### Steps to reproduce

1. Set the Ancient Spellcraft config to "Battlemage Keep Rarity"=50 and "Ancient Vault Structure"=50
2. Create a new world to explore in Creative
3. Follow along the Coastline of rivers, lakes, or oceans to find Battlemage Forts
4. Notice that occasionally the dirt layer under them is misplaced to the side
5. Notice that occasionally a Battlemage Fort and Ancient Vault end up being placed to overlap one another

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
I hope this was fixed since 1.7.x but reopen this if you encounter it again
