### ISSUE TITLE
[Bug] Pocket Library displaces/destroys nearby Structures when it is removed

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

After placing a Pocket Library right next to a Building, and then packing up the Pocket Library.. part of the nearby Structure has been destroyed.

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/e46243b5-f1a0-4780-a0cf-0c3e06529d56)

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/70be9eec-d2c5-4d58-bea9-f59f178fce80)

Part of the issue is that it can give access to areas behind Arcane Walls

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/b8b0c120-d294-454a-9a39-d0fa1aa93fab)

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/d9626e26-57fb-4f7f-9175-20afe8c445fc)

### Expected behaviour

I would expect that after packing up Pocket Library, that the replaced blocks would return to their original state.

Optionally, if placed too close to a existing Structure then the casting would be blocked with a message "The Pocket Library cannot be next to a existing structure."

### Steps to reproduce

1. Join a Server
2. Cast Pocket Library while standing just outside of the Arcane Wall in a Sage Hill or Ancient Vault
3. Pack up the Pocket Library by recasting the spell while inside.
4. Notice the effect on the structure.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by KnightCa** [comment]
It would also be wonderful to have the middle floor block of the Pocket Library be a Arcane Workbench to gain easy access to library books.

**Comment by WinDanesz** [comment]
I was considering a workbench too, but was thinking about having a lower tier artefact for that. Won't mind adding a workbench just by default tho

**Comment by KnightCa** [comment]
Would be really nice, so that it reforms when you put it in a new place

**Comment by KnightCa** [comment]
Pocket Library can also break a hole into the side of your Pocket Dimension:

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/a39c2413-272e-4061-b2a0-b85ebff00596)

**Comment by KnightCa** [comment]
I'd suggest adjusting the Pocket Library to work like this (avoiding any structure conflict/destruction):

Either limit its creation the same way that Ice Tower is (wont cast if it conflicts with another block)

or even more preferably..

Pocket Library would be the size of a single block (ie size of a Arcane Workbench). This will make it easy to place without worrying about the impact on other structures.

Appearance would be a of a Arcane Workbench with bookcases on the side of the Workbench:
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/857de4ed-35fe-400d-8ec0-9e4646e0874c)
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/630cbefe-7f76-47ea-b3c1-cd1ecc3fb0ab)

The Pocket Library would have a GUI that lets you interact in the same way that a Arcane Workbench (Wand spell slot and upgrade assignment / Wizard Armor and Wand mana recharge), Bookcase (add/remove spellbooks), and Lectern (view descriptions of spells / sort spells) by way of a button on the GUI. The storage would be equal to at least 12 Bookcases (144 items, configurable in config). Only the caster could interact with the GUI.

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/065a2bd9-b3e0-4c29-93cb-d6247a77a6f5)

The reason for the caster only access is to avoid griefing (either intentionally or accidently having others take your items).

The Pocket Library would disappear when either broken or when the Pocket Library is again cast by the same caster. At a later time, when the caster re-summons the Pocket Library by casting the spell, it would have the same contents. Thus, if a explosion, another player, or a mob destroyed the Pocket Library (or the caster lost track of where his Pocket Library got set down).. it would be easy to regain access to it (simply cast Pocket Library again to un-summon it if it still exists, and then again to re-summon it).

This way of handling the Library would give a similar effect to Pocket Dimension (easy access from anywhere with secure contents) and a Arcane Workbench/Lectern/Bookcase (with far more storage ability).

Possible Artifact ideas:
1. Expanded Storage: If the Pocket Library is summoned while wearing this item, then a additional GUI button lets you access a secondary storage area of almost the same size that can accept spellbooks, scrolls, and other items (anything listed in the config for Bookcases to be able to store). These items would not be available on the main GUI and thus could not be assigned to Wand spell slots (without moving them to the main storage area). It would be wonderful if you could view the contained items and sort them in a similar way that the Bookcase GUI allows you to do when looking at the Arcane Workbench GUi. If this Artifact is not worn when summoning the Pocket Library, the secondary storage is not available.
2. Access Expansion: If the Pocket Library is summoned while wearing this item, then its GUI can be accessed by any player. A nice way to be able to share it with fellow Wizards.

**Comment by KnightCa** [comment]
@WinDanesz With the latest release (ancientspellcraft-1.12.2-1.5.11-PreRelease-4f214c5), the Pocket Library doesn't check for the following blocks (and thus will result in their destruction if present):
1. Chests
2. Stones of Transportation
3. Imbuement Altar
4. Arcane Workbench
5. Lectern
6. Arcane Anvil
7. Mystic Lectern

I'm sure there are quiet a few more. I'm worried that players will lose quiet a few things when these things get erased.

Can we adjust the allowed blocks it can replace be a configurable whitelist, with included defaults like minecraft grass, snow, flowers, dead bush, ferns?

**Comment by KnightCa** [comment]
Also, please have text sent to chat when deployment is blocked by obstacles. Perhaps similar to Ice Tower?
