### ISSUE TITLE
[Bug] Minion spells are given the Utility type

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

The following spells are categorized as Utility type spells, rather than Minion type spells.

Conjure Creeper
Conjure Greater Sentry
Conjure Lesser Sentry
Nether Guard
Summon Zombie Pigmen

### Expected behaviour

These spells summon minions and thus should be the minion type.

### Steps to reproduce

1. Join a Server
2. Look at the spell type for the listed spells.
3. Note that they are Utility, despite summoning minions.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
I probably won't change Conjure Greater Sentry, Conjure Lesser Sentry, they are too different and could cause confusion if someone checks spell types (in code)
