### ISSUE TITLE
[Bug] Arcane Workbench causes Wand to lose gained spell slots from Wand Attunement Upgrades after using the X

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Arcane Workbench causes a Wand to lose gained spell slots from Wand Attunement Upgrades after using the X.
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/c1aedbff-1e16-493a-8f35-4f731ab23801)

### Expected behaviour

I expected the Wand Attunement upgrades to continue providing extra spell slots in the Wand when using the X to clear assigned spells.

### Steps to reproduce

1. Join a Server
2. Access a Arcane Workbench
3. Add 3 Attunement wand upgrades to a Master Wand (Wand shows 8 spell slots on Workbench and 8 spell slots on Wand)
4. Use the X button (clears all assigned spell slots)
5. Try to add more 8 spells and apply them (Wand shows 8 spell slots on Workbench and 5 spell slots on Wand)
6. Wand is unable to benefit from anymore than 5 spell slots assigned to it, despite the Workbench showing 8 spell slots

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
This is a base mod feature (and bug)

**Comment by KnightCa** [comment]
@WinDanesz It looks like this bug is fixed now ;)
