### ISSUE TITLE
Maybe it's a bug?

### ISSUE THREAD

**Issue by MrShaNEk** [WinDanesz/AncientSpellcraft#22]
![image](https://user-images.githubusercontent.com/66978725/111464505-cdd51680-875b-11eb-8acd-71cd9709a162.png)
I've already Researched "stone Tablet" in "Sphere of Cognizance". Is there something wrong or is it a bug??

**Comment by WinDanesz** [comment]
Hi, Please send a screenshot of the tooltip text of that stone tablet. Since the 1.2.2 update, not all stone tablets contain spells, only those which has the "Spell" label (they have a gold color). The others can be activated simply by right clicking them by holding the button for 8 seconds

**Comment by MrShaNEk** [comment]
> Hi, Please send a screenshot of the tooltip text of that stone tablet. Since the 1.2.2 update, not all stone tablets contain spells, only those which has the "Spell" label (they have a gold color). The others can be activated simply by right clicking them by holding the button for 8 seconds 


Oh, there are no incantations on that stone tablet. I don't know it need a "Spell" label, Thank you!
by the way,it's a wonderful mod！
