### ISSUE TITLE
[Bug] Curse of Death does not result in death

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I've been looking into Curse of Death. I used a Dispenser to curse myself, so that I could check to see if it still leaves no grave from Corail Tombstone. I saw the curse marker and eventually it counted down (3 days minecraft time), but then I did not die (yep in Survival).

### Expected behaviour

I expected that Curse of Death would kill the player and result in a tombstone (if using Corail Tombstone) with the equipment carried at death.

### Steps to reproduce

1. Join a server
2. Use a dispenser to apply Curse of Death to yourself.
3. Wait 3 days to see the Curse timer run out.
4. No death results.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

### Other mods

tombstone-4.6.2

**Comment by KnightCa** [comment]
@WinDanesz After putting the Curse of Death in the Dispenser and hitting myself with it, I get the below icon appear but with no count-down timer. I waited for several hours in Survival mode on Difficulty Easy to see if it would kill the player.. but so far nothing.

Does this look right?

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/b5bd68ce-20ac-4efd-aec7-8c8b7b575c9c)

**Comment by WinDanesz** [comment]
Don't wait hours, just use `/effect yourplayername ancientspellcraft:curse_of_death 5`

**Comment by WinDanesz** [comment]
If you want to test the effect. I'll check the timer

**Comment by KnightCa** [comment]
Giving the effect worked. I'd appreciate checking the timer for getting the
effect, as it appears to be XX'd out.

**Comment by KnightCa** [comment]
Confirmed that this is already working correctly in the new release. When the time period is too long, you get a XXX for the countdown until it reaches a low enough time period.
