### ISSUE TITLE
[Bug] Spell Blade and Possession fails to activate on target

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When holding a Runic Shield and fully upgraded Spell Blade, and trying to cast Possession on a target (sneak right-clicking).. the spell acts as if casting but no Possession is made of target.

Using a Wand with Possession works fine on the same target.

### Expected behaviour

I expected the Possession spell to work just as it does from the Wand.

### Steps to reproduce

1. Join a Server
2. Equip Battlemage armor, Runic Shield, and Spell Blade with the spell Possession
3. Target a Zombie and notice the lack of effect.
4. Equip a Wand with the spell Possession
5. Target a Zombie and notice the expected effect

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
This is because possession can't be applied while sneaking
```
        if (possessor.isSneaking()) {
            return false;
        }
```
But you can sneak first to start casting, release sneak while the spell is charging up and then it works. There isn't much I can do and this applies to other similar spells. The workaround should work, just requires better coordination

**Comment by KnightCa** [comment]
@WinDanesz While the work around does indeed work, it's difficult to cast a concentration spell in the middle of a intense fight with multiple mobs. The keybind suggestion for casting a spell with the Spell Blade would solve this sort of situation.

The hope would be to have these options:
1. Left-click to attack with Spell Blade (works as is)
2. Right-click to block with Runic Shield (works as is)
3. Right-click + C (configurable keybond) to cast spell with Spell Blade (disables Runic Shield use while holding keybind)
4. Hold Right-click + C to charge up and cast spell requiring Charge-up (disables Runic Shield use while holding keybind)

This would make casting similar to how it has worked with Spell Blade in the past (left-click to attack, right-click to cast) while allowing Runic Shield blocks (casting with Spell Blade becomes a keybind).

Possible actions I can imagine:
1. Sprinting (holding down Ctrl+W) while charging towards a boss. As you continue to sprint towards the boss, you alternate between blocking with Runic Shield (right-click + Ctrl+W) as projectiles come towards you from Boss and casting projectile spells from Spell Blade (right-click+C + Ctrl+W) towards the still distant boss.
2. Sneaking (holding down Shift+W) while crossing a dangerous narrow bridge in the Nether. As you continue to sneak across the bridge, you alternate between blocking with Runic Shield (right-click + Shift+W) as projectiles come towards you from a distant Ghast, trying to melee Spell Blade the incoming fireballs (left-click + Shift+W), and casting projectile spells from Spell Blade (right-click+C + Shift+W) towards the Ghast.
3. While in the middle of a fight with multiple mobs, you block Skeletons with Runic Shield (right-click), melee Spell Blade (left-click) with Zombies, cast Magic Missile at Skeletons (right-click+C), then cast a Mana Vortex by charging up a spell from Spell Blade (hold right-click+C).
