### ISSUE TITLE
[Bug] Runic Shield makes it hard to target foes with spells cast from Spell Blade

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

While holding a Runic Shield and Spell Blade, it is hard to target mobs with spells (sneak-right-click) due to the shield blocking the area of view.

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/fa357264-9449-44a6-9d5b-d5520435693b)

### Expected behaviour

I expected the Runic Shield to not be in the field of view when casting spells from the Spell Blade (similar to what happens when casting while holding a Wand and casting.

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/a95ad188-d11f-4193-82d0-6ed4d6390e1d)

### Steps to reproduce

1. Join a Server
2. Equip Battlemage armor, a Runic Shield in offhand, a Spell Blade with Magic Missile, and a Wand with Magic Missile
3. Sneak-right-click with the Spell Blade to cast at a mob (notice the blocked vision)
4. Sneak-right-click with the Wand to cast a mob (notice the clear vision field)

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-54bfadc

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
This is a bit unclear, you either cast, or block, but can't do the two at the same time.
What's valid is that while you are blocking (just right click), you don't see a lot. I lowered the shield now a bit. While sneak-right clicking, you can't block with the shield - the casting takes precedence, so these shouldn't happen simultaneously.

**Comment by KnightCa** [comment]
@WinDanesz While using the latest Ancient Spellcraft preview (ancientspellcraft-1.12.2-1.5.11-PreRelease-4f214c5). I had a variety of issues trying to cast spells with the runic shield and spell blade combo.

**Observed behavior**
While holding a Runic Shield and Spell Blade, it is difficult to target mobs with spells from the Spell Blade:

1. When right-clicking to cast a spell, the runic shield rises instead and no spell is cast.
2. When shift-right-clicking, the spell casts.

Currently there is no way to have the Spell Blade in main hand and Runic Shield in off-hand and do the following:
1. Without sneaking, cast a spell using the Spell Blade.
2. Sneak while blocking with the Runic Shield, without casting a spell using the Spell Blade (for example, trying to block a Ghast while sneaking as you move across a bridge to avoid accidentally falling off the edge).

**Expected behavior**
I expected that while holding the Spell Blade and Runic Shield, to have a way to do a Melee attack (left-click), block (right-click), and cast a spell with Spell Blade without sneaking.

I hoped to have the same behavior while sneaking.

**Possible Solution**
Create a configurable keybind for either the Runic Shield Block or Spell Blade Cast. Of the two options, I'd suggest creating a Spell Blade Cast keybind (such as C + right-click) that works when either sneaking or not-sneaking.

**Note**
It's possible that I missed that there is already a way to cast a spell with the Spell Blade while holding the Runic Shield and not sneaking?
