### ISSUE TITLE
[Bug] Dispel Item Curse fails to dispel non-vanilla curse enchantments

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

While the spell dispels item vanilla curses from worn armor or off-hand items, it doesn't effect non-vanilla curses.

**Vanilla (working)**:
Curse of Binding
Curse of Vanishing

**So Many Enchantments**:
Bluntness
Curse of Decay
Curse of Holding
Curse of Inaccuracy
Curse of Possession
Curse of Vulnerability
Cursed Edge
Heavy Weight
Inefficient
Instability
Powerless
Rusted
Unpredictable

**Charm**:
Curse of Rusting
Curse of Clumsiness
Curse of Haunting
Curse of Harming

### Expected behaviour

I expected the spell to remove cursed enchantments from non-vanilla sources.

### Steps to reproduce

1. Join a Server
2. Try to castle Dispel Item Curse on a off-hand item enchanted with one of the non-vanilla curses.
3. Notice the lack of effect

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-4f214c5

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
I'm not familiar with the registry names of these mods' enchantments, but I reworked the spell to allow adding them to a configuration list. 
If you feel like, you can help by getting a list of them so that I can add them to the default list.
```

		@Config.Name("Curses that the Dispel Item Curse spell can remove. Should work with modded enchantments as well.")
		@Config.RequiresMcRestart
		public String[] dispel_item_curse_list = {
				"minecraft:vanishing_curse",
				"minecraft:binding_curse"
		};
```
