### ISSUE TITLE
[Bug] Runeword descriptions are not consistent and have missing or inaccurate data

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

The Runeword spell descriptions do not seem to be consistent (sometimes incorrect or missing duration in seconds, range, or duration).

These are the current Runeword Descriptions:
- Arcane = "Imbue the Spell Blade with arcane energy, causing your next hit to deal 70% weapon damage and bypass armor."
- Blast = "The next hit of the Spell Blade blasts the enemy away over a large distance."
- Briar = "Hitting an enemy with the Spell Blade has a chance to cause thorn bushes to sprout near the enemy."
- Disarm = "The next attack with the Spell Blade will disable the targeted player's held items for 3 seconds."
- Displace = "The next 3 hits of the Spell Blade teleports the target to a nearby location."
- Empower = "Instantly charges the Spell Blade, causing its next attack to trigger its empowered effect."
- Endure = "Hold your ground for 5 seconds, reinforcing your defense."
- Exorcise = "Blesses the Spell Blade, causing the next 3 attacks deal 50% more damage against undeads, weaken them and set them on fire."
- Fury = "Hitting enemies with the Spell Blade temporarily increases it's melee damage by up to 50%."
- Ignite = "The next hit with the Spell Blade sets the target on fire for a long duration."
- Imbue = "Imbue the Spell Blade with a potion from the hotbar for the next few hits."
- Implode = "The Spell Blade pulls in all nearby enemies and deals a small amount of damage to them."
- Meditate = "Meditates to restore the energy of a Runic Shield in the offhand. Continuous spell."
- Pull = "Greatly increases the attack range of the Spell Blade and pulls the enemy for the next 2 attacks."
- Push = "Greatly increases the attack range of the Spell Blade and pushes the enemy with a concussive beam."
- Reach = "Greatly increases the attack range of the Spell Blade for the next 3 hits."
- Restoration = "Draw power from the Spell Blade, restoring 10% missing health."
- Sealbreaker = "Dispels an arcane wall which protects a structure."
- Shatter = "Empowers the Spell Blade, causing its next hit to disable the shield of the enemy."
- Sol = "Hitting an enemy with the Spell Blade blinds it for 5 seconds."
- Strength = "Temporarily empowers you with Strength."
- Suppress = "The next 3 hits of the Spell Blade applies a stacking Magical Exhaustion effect on the target for 3 seconds. If the target is already affected, some of it backfires on the Battlemage too."

**Runewords in Development:**
- Expose
- Sacrifice

### Expected behaviour

These are the suggested Runeword Descriptions to change to keep consistency **(changes in bold)**:
- Briar = "Hitting an enemy with the Spell Blade has a **60%** chance to cause thorn bushes to sprout near the enemy **for 5 seconds**."
- Endure = "Hold your ground for **8** seconds, reinforcing your defense."
- Exorcise = "Blesses the Spell Blade, causing the next 3 attacks deal 50% more damage against undeads, weaken them and set them on fire **for 10 seconds**."
- Fury = "Hitting enemies with the Spell Blade temporarily increases it's melee damage by **5% per hit, to a maximum of 100% increase**."
- Ignite = "The next hit with the Spell Blade sets the target on fire for **13 seconds**."
- Imbue = "Imbue the Spell Blade with a potion from the hotbar for the next **10** hits."
- Implode = "The Spell Blade pulls in all **enemies within 12 blocks** and deals **3** damage to them."
- Meditate = "**Continuously** meditates to restore the energy of a Runic Shield in the offhand."
- Sealbreaker = "Dispels an arcane wall **within 6 squares** which protects a structure."
- Sol = "**The next 3 hits** with the Spell Blade blinds **the target** for 5 seconds."
- Strength = "Empowers you with Strength **for 20 seconds**."
- Suppress = "The next 3 hits of the Spell Blade applies a stacking Magical Exhaustion effect on the target for **2** seconds. If the target is already affected, some of it backfires on the Battlemage too."

### Steps to reproduce

1. Look at the descriptions for the runeword spells and notice how they differ in what information they show.
2. Notice how some of the descriptions duration or other information is no longer accurate.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-4f214c5

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
Thanks for compiling these!
