### ISSUE TITLE
[Bug] Runeword: Disarm not useful vs mobs (only for PVP)

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Description "The next attack with the Spell Blade will disable the targeted player's held items for 3 seconds."

This looks to only be useful vs other players. Would be nice to have this useful against mobs.

### Expected behaviour

I would have expected Disarm to work against any mobs carrying held items (swords, shields, wands, etc)

### Steps to reproduce

1. Join a non-PVP server
2. Try to figure out a use for this spell.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-4f214c5

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
Mobs that use shields always use custom AI, if the shield disablement is not already supported, then there is nothing we can do about it from our side

**Comment by KnightCa** [comment]
Gotcha, so it sounds like this is designed to be used against Players.
