### ISSUE TITLE
[Bug] Runeword: Meditate has no spell icon and a odd casting appearance

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

The Spell image is missing for Runeword: Meditate
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/cfb7eb18-6aae-46b6-b7f0-355773440ca5)

In addition, the spellcasting shows a odd rotating purple square while casting (unlike the other Runewords)
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/047e64fd-278f-4720-893d-d291a8064cff)

### Expected behaviour

I expected the spell icon to be the same as the other Runewords:
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/e8594f5c-67a2-4008-ad82-051eb6ae161a)

I expected spellcasting to look like other Runewords.

### Steps to reproduce

1. Join a Server
2. Look at the icon that appears with Runeword: Meditate selected
3. Cast the spell and observe the appearance of casting.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-4f214c5

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by KnightCa** [comment]
Likewise Runesmithing: Improve needs a spell icon
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/1b08850f-7d30-4319-b76d-c2cf60b851fa)

Works great though

**Comment by WinDanesz** [comment]
That weird circle must be coming from an another addon

**Comment by WinDanesz** [comment]
I guess one of Zetta's mods adds it
