### ISSUE TITLE
[Bug] Runewords and Runesmithing spell json configurations

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

The following spells are set differently than the general defaults for Runewords..

**Set to be available for NPC Battlemages**: Don't seem useable by NPCs.
- Runesmithing: Improve: Enchants a tool in an Arcane Anvil with Efficiency 2. It also always restores 5% durability to the tool.
- Imbue: Imbue the Spell Blade with a potion from the hotbar for the next 10 hits
- Meditate: Continuously meditate to restore the energy of a Runic Shield in the offhand.
- Sealbreaker: Dispels an arcane wall within 6 squares which protects a structure.

**Sealbreaker** does not allow command casting.

**Set to not be available to NPC battlemages**: Seem useable by NPCs
- Briar: Hitting an enemy with the Spell Blade has a 60% chance to cause thorn bushes to sprout near the enemy for 5 seconds.
- Pull: Greatly increases the attack range of the Spell Blade and pulls the enemy for the next 2 attacks.
- Reach: Greatly increases the attack range of the Spell Blade for the next 3 hits.
- Sacrifice: Next hit, Health Cost for Damage Increase
- Sol: The next 3 hits with the Spell Blade blinds the targeted player for 5 seconds.
- Supress: The next 3 hits of the Spell Blade applies a stacking Magical Exhaustion effect on a targeted player for 2 seconds. If the target is already affected, some of it backfires on the Battlemage too.

### Expected behaviour

I would have expected them to be set as..

**Set to be available for NPC Battlemages**: Don't seem useable by NPCs. I would have thought these would have been set to No for NPCs.
- Imbue: Maybe allow them a random harmful potion effect when used by NPCs?
- Sealbreaker: Maybe allow them to destroy Arcane/Spectral Wall used by players to keep them at bay?

I would have expected **Sealbreaker** to be allowed for command casting.

**Set to not be available to NPC battlemages**: Seem useable by NPCs. I would have thought these would have been set to Yes for NPCs.

### Steps to reproduce

1. Look at Ancient Spellcraft assets/spells json configurations.
2. Compare the settings to other Runeword spells.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.5.11-PreRelease-4f214c5

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by KnightCa** [comment]
I couldn't figure out how to test the following Runewords: Are these only for use against players?
- **Fury**: multiple hits didn't seem to be increasing damage

The following Runewords can only be used against players:
- **Shatter**: Since the shield mechanic for mobs using Shields is always a custom AI component, then the spells affecting shields can only be used against players.
- **Sol**: Only players can be affected by the blinded condition.
- **Suppress**: Magical Exhaustion is a condition that only be applied to players.

**Comment by WinDanesz** [comment]
Magical Exhaustion works on NPCs, blinding too because of EbWiz
