### ISSUE TITLE
My own server crash

### ISSUE THREAD

**Issue by Nyxkoh** [WinDanesz/AncientSpellcraft#24]
My server crash, i think it was a problem of ancient spell craft, i send here my crash log. 
[crash-2021-03-27_16.36.33-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/6215923/crash-2021-03-27_16.36.33-server.txt)

**Comment by WinDanesz** [comment]
This issue was fixed in 1.1.3, you are using 1.1.2. Update your mod version. Cheers.
