### ISSUE TITLE
[Bug] Ancient Compendium of the Arcane Arts shows error

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When opening the Ancient Spellcraft guidebook "Ancient Compendium of the Arcane Arts", it shows a error:

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/d58ee041-9f58-43a1-95c0-23dc95c098a5)

Then when clicking on any of the patchouli guide book links, Minecraft crashes.

### Expected behaviour

I expected the Ancient Spellcraft guidebook to allow reading the links without crashing.

### Steps to reproduce

1. Join a Server
2. Try to open the AS guide book
3. Click on a link

### Crashlog

https://mclo.gs/n9jwj9B

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.6.0

### Forge version

1.12.2-forge-14.23.5.2860

### Other mods

Patchouli-1.0-23.6

**Comment by WinDanesz** [comment]
This item is now removed, documentation was moved to the Wizard's Handbook
