### ISSUE TITLE
[Bug] Runeword: Expose has missing name and description

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Runeword: Expose is named as spell.ancientspellcraft:runeword_expose
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/4eace9bb-fddc-4ff3-b367-0230e1cc29ff)

And it's decription is spell.ancientspellcraft:runeword_expose.desc
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/034afc93-d78a-4c68-87a6-317cb7b124e5)

It appears that a entry for this Runeword was left off the language file:: 
  AncientSpellcraft-1.12.2-1.6.0.jar\assets\ancientspellcraft\lang\en_us.lang
- spell.ancientspellcraft\:runeword_expose=Runeword: Expose
- spell.ancientspellcraft\:runeword_expose.desc=???

### Expected behaviour

I expected the Runeword to appear like others with a description.

### Steps to reproduce

1. Join a Server
2. Look at the Spell Name / Description for Runeword; Expose

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.6.0

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment]
Fixed by 7503e31def9d6ecb1584fbb560ba3c4385cfcd45
