### ISSUE TITLE
[Bug] Battlemage Camps are often set too low in the ground and have their entrances blocked

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/AncientSpellcraft#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Battlemage Camps are often set 1 block too low in the ground, which means the Battlemage inside cannot get out to fight unless the entry is cleared of the block in the way. This makes them too easy to defeat since they are stuck inside until the player releases them.

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/99ad705c-5bea-4c1f-872c-863f4c0c0f37)

### Expected behaviour

I expected a Battlemage in a Camp to be able to exit freely on their own, when they detect players nearby.

### Steps to reproduce

1. Join a Server
2. Find a Battlemage Camp
3. Notice how the occupant cannot exit the Camp without help.

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.6.3

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by KnightCa** [comment]
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/0f709e95-2ce7-434d-8e41-1879ab46671c)

**Comment by KnightCa** [comment]
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/756ac779-4273-4879-abd3-8781b49afb62)

**Comment by KnightCa** [comment]
This can likely be fixed by giving a extra 1-2 lines of air in front of the Camp, so that the occupant has room to exit.

**Comment by RulerOfEternity** [comment]
There are structure generation problems with all AS structures I've noticed, I think I mentioned them in the Discord too, just wanted to put that in the thread

**Comment by KnightCa** [comment]
![image](https://github.com/WinDanesz/AncientSpellcraft/assets/51968609/31d0459b-48ba-4897-bf44-b3b260965f0e)

**Comment by KnightCa** [comment]
> There are structure generation problems with all AS structures I've noticed, I think I mentioned them in the Discord too, just wanted to put that in the thread

There are other tickets for the other structures.

**Comment by KnightCa** [comment]
This appears to be fixed in latest release.
