### ISSUE TITLE
[Bug] Visual bug within the Pensive

### ISSUE THREAD

**Issue by RulerOfEternity** [WinDanesz/AncientSpellcraft#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

When you put in XP, leave the world and rejoin, the XP (the green liquid) is gone, this is only a visual bug though, you can still retrieve the XP. If you have put more than 30 XP in the Pensive you lose everything above that (See Issue #158)

### Expected behaviour

The Green liquid should stay visible upon rejoining the world, I've found setting up modded servers to be too complicated so I can't say on how it works over there.

### Steps to reproduce

1. Get a pensive
2. Put XP in it
3. Leave world and rejoin
4. Visually gone, but you can still retrieve the XP, again, if you put more than 30 XP then you're out of luck, everything's gone, but that has been mentioned in another issue.

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.6.3

### Forge version

1.12.2 - 14.23.5.2860

### Other mods

![image](https://github.com/WinDanesz/AncientSpellcraft/assets/76789367/7f0cc8ab-b6a8-4e0b-b963-44010c64efcd)

**Comment by WinDanesz** [comment]
fixed in 1.7.2
