### ISSUE TITLE
[Question] AncientSpellcraft with older version of AncientWarfare2

### ISSUE THREAD

**Issue by Taknax** [WinDanesz/AncientSpellcraft#25]
I use the older version of AncientWarfare2 (2.7.0.704), becuase i didnt get managed let the new amazing AW2 work lagfree. Does the new version of AncientSpellcraft (1.1.3) work with the older version of AW2? If yes, do im gonna miss feature?

**Comment by WinDanesz** [comment]
Ancient Warfare2 and Ancient Spellcraft are not related at all (except for me being one of the developers of these two mods). . I was considering to add AW2 exclusive content to AS, but as of now there is nothing like that in place. AS is an Electroblob's Wizardry add-on, AW2 is a standalone mod. So the versions doesn't matter.

**Comment by Taknax** [comment]
O ok. Are the wizard tower structures from AS not dor AW2 bevause i have both installed?

**Comment by WinDanesz** [comment]
AW2 adds the wizard towers and the other compat structures and the spellcaster NPCs.

**Comment by Taknax** [comment]
That answer my Question. Thanks for the information.
