### ISSUE TITLE
[Bug] 1.7.0 crashes on startup with ClassNotFoundException

### ISSUE THREAD

**Issue by brisingraerowing** [WinDanesz/AncientSpellcraft#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

Crash on startup

### Expected behaviour

No crash on startup

### Steps to reproduce

1. Load EBW and AS
2. Start Game

### Crashlog

https://gist.github.com/brisingraerowing/f08252a0e3b7e9b7dfe2509787d1dbd9

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.7.0

### Forge version

1.12.2 - 14,23,5,2860

**Comment by YukiLucky** [comment]
Yeah, having this same error after updating to 1.7.0 :/

**Comment by WinDanesz** [comment]
Until a fix is released, please use the previous version
