### ISSUE TITLE
where are the grand stone tablets ?

### ISSUE THREAD

**Issue by skaparinn** [WinDanesz/AncientSpellcraft#26]
Hello, I just discovered this mod but I don't know where to find tablets, I did some dungeons but nothing at all. I am using version 1.1.3 of Ancient Spellcraft. Someone can help me ?

**Comment by WinDanesz** [comment]
Stone tablets can he found where you can find Wizardry stuff in general - wizard tower chests, obelisks, shrines, mineshaft chests  dungeon chests, plus whatever you configure in the settings, you can set up more loot table inject targets.

**Comment by skaparinn** [comment]
Ok, thanks a lot.
