### ISSUE TITLE
Summon Skeleton Horse not working/crashing game

### ISSUE THREAD

**Issue by Rockpaw** [WinDanesz/AncientSpellcraft#27]
A friend of mine noticed that on our server the Summon Skeleton Horse spell crashed his game when he used it. I then started a single player world to test out if any of the other mods I was using where causing the issue. When I started the game with only Electroblobs Wizardry and Ancient Spellcraft I still had the issue. 
If I use a scroll it does not crash and nothing happens, but if I use a wand it crashes. 
[crash-2021-04-29_18.04.51-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/6401897/crash-2021-04-29_18.04.51-server.txt)

**Comment by WinDanesz** [comment]
fixed in 32b638ef5e768867deda7ccf978c2fe505c8ae8e
