### ISSUE TITLE
My game can't start after deleting the twilight forest mod

### ISSUE THREAD

**Issue by minebloxian334** [WinDanesz/AncientSpellcraft#29]
so when I deleted twilight forest since I felt like I will not do anything with it then vanillafix told me this after deleting it

https://paste.dimdev.org/jeyayotoqo.mccrash

**Comment by WinDanesz** [comment]
Did you find a resolution for this since you've closed the issue?

**Comment by minebloxian334** [comment]
> Did you find a resolution for this since you've closed the issue?

yes found it it was the avaritia mod that was making my game laggy and might be preventing my game to play
