### ISSUE TITLE
Unable to list biomes

### ISSUE THREAD

**Issue by TheMightyMcGrew** [WinDanesz/AncientSpellcraft#3]
The  /listbiomes command gives the error "An unknown error occured while attempting to perform this command"

**Comment by WinDanesz** [comment]
it would be useful to see the relevant parts of your debug.log, it probably had some errors

**Comment by TheMightyMcGrew** [comment]
Id love to help you in doing that, but if you could be so kind as to tell me where/how to find the debug.log
