### ISSUE TITLE
How do you find charged astral diamond?

### ISSUE THREAD

**Issue by minebloxian334** [WinDanesz/AncientSpellcraft#30]
I've been looking for it and tried many wikis and videos and I can't seem to find any someone did say that it can be obtain by using one of this addons spells but they didn't say which one

**Comment by WinDanesz** [comment]
It's documented here https://github.com/WinDanesz/AncientSpellcraft/wiki/Essence-Extraction#imbuement-altar

**Comment by minebloxian334** [comment]
> It's documented here https://github.com/WinDanesz/AncientSpellcraft/wiki/Essence-Extraction#imbuement-altar

thanks for the info
