### ISSUE TITLE
Biome finding does not know how to handle duplicate indexes.

### ISSUE THREAD

**Issue by thakyZ** [WinDanesz/AncientSpellcraft#31]
The `Will O' Wisp` spell and the `/listbiomes` command ends up erroring when trying to find a biome when there happens to be the same biome at the same key. I was using MC Eternal and only added `OptiFine` and `Reload Audio Device` as mods.

The error report reads as: [https://gist.github.com/thakyZ/cec169cd3f4eef714765858339330a1e](https://gist.github.com/thakyZ/cec169cd3f4eef714765858339330a1e)

**Comment by WinDanesz** [comment]
Thanks for the crash log, will fix that for the next update

**Comment by WinDanesz** [comment]
the same error was thrown for both the spell and the command?

**Comment by thakyZ** [comment]
> 
> 
> the same error was thrown for both the spell and the command?

Yes it was.
