### ISSUE TITLE
Essence Extraction does not respect claims.

### ISSUE THREAD

**Issue by jazoobio** [WinDanesz/AncientSpellcraft#32]
As said in title, essence extraction can be used to destroy imbuement altars in claims. I would greatly appreciate if this was fixed.

**Comment by WinDanesz** [comment]
Ok, will add this for the next update. 
A related question, does the Void Pearl + Black Hole spell respect your claims? Because if it doesn't, then I won't apply the same logic here.

**Comment by jazoobio** [comment]
Yes, the Void Opal + Black Hole seems to respect my claims, thank you.
