### ISSUE TITLE
POCKET DIMENSION WITH TRANSPORTATION PORTAL

### ISSUE THREAD

**Issue by MCKIT77** [WinDanesz/AncientSpellcraft#35]
when using transportation portal with the ancient compass, if you have multiple circles remembered and go into pocket dimension, it erases your remembered stone circles. otherwise love this mod and it is flat out amazing

**Comment by WinDanesz** [comment]
I'll have a look into this, will be fixed for the update

**Comment by WinDanesz** [comment]
The spell had several rewrites since then. Please reopen if you still have this issue with the latest version
