### ISSUE TITLE
Evergrowing Crystal outputs

### ISSUE THREAD

**Issue by Pelirow** [WinDanesz/AncientSpellcraft#37]
Tested 25+ Everlasting Crystals in multiple biomes and only ever got 3 drops: 85% of the time it was Emerald, 10% of the time it was Diamond, and 5% of the time it was [Redacted]. Tooltip specifies the Everlasting crystal should produce a random crystal when right clicked.

**Comment by WinDanesz** [comment]
Biomes don't affect what drop you get from the crystal. You got the chances about right and it can only drop emeralds diamonds and astral diamond shards intentionally.
