### ISSUE TITLE
Updating AS for an existing world gave me this notice

### ISSUE THREAD

**Issue by Pelirow** [WinDanesz/AncientSpellcraft#38]
![Capture](https://user-images.githubusercontent.com/8356065/127177161-eeb801f6-c3f4-4216-9a26-cb8d2a987445.PNG)

**Comment by WinDanesz** [comment]
Frost nova's sound was changed from a single sound to a sound loop (start, loop, end) so the original sound was removed. The error can be annoying but it should only pop up once.
