### ISSUE TITLE
Arcane Compound recipe JEI issue

### ISSUE THREAD

**Issue by WinDanesz** [WinDanesz/AncientSpellcraft#45]
https://cdn.discordapp.com/attachments/444995978823467009/869893943347806258/2021-07-28_12.47.34.png

**Comment by Pelirow** [comment]
I have no problems seeing the recipe, it cycles through all the variations possible. I'll follow up with the person in question about shaders or optifine.

![Arcane Compound Recipe](https://user-images.githubusercontent.com/8356065/127340564-f118f6ee-2bbe-4c62-b757-4810e7984d31.PNG)
