### ISSUE TITLE
Will o Wisp spell crash for duplicate ids

### ISSUE THREAD

**Issue by WinDanesz** [WinDanesz/AncientSpellcraft#47]

**Comment by WinDanesz** [comment]
``
[message.txt](https://github.com/WinDanesz/AncientSpellcraft/files/6895906/message.txt)

**Comment by Pelirow** [comment]
Dan, this is also covered in issue 31, FYI. There's a crash report in there that may be of further help.

It's probably also related to the still open Issue 3 that probably either should be followed up on with the poster, or simply closed.

**Comment by WinDanesz** [comment]
Duplicate of #31
