### ISSUE TITLE
Friendly wizards despawning

### ISSUE THREAD

**Issue by smoothuk** [WinDanesz/AncientSpellcraft#49]
Minecraft version: 1.12.2
Ancient Spellcraft version: 1.2.0
Wizardry version: 4.3.4
Environment: Singleplayer

Issue details: Friendly wizards found in towers are incorrectly named 'unknown' and despawn when chunk is unloaded, if Ancient Spellcraft is installed. 

To reproduce- 1) Find a wizard in his tower. 2) Leave the area for a while. 3) Return to where you found him. 4) Be sad because dad went to get magic crystals and never came back.

**Comment by WinDanesz** [comment]
Thanks, fixed for the next update.
