### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Gaber373** [WinDanesz/AncientSpellcraft#5]
The world was an already existing one now ill try with a new one with the mods then if it doesn't work with just ancient spellcraft
[the crash report](https://pastebin.com/CJ0BkdLz)

[Loading the new world the error kinda changed](https://pastebin.com/hejzyV7U)

[now with just wizrdry and as](https://pastebin.com/bXeSvVuJ)

**Comment by WinDanesz** [comment]
The crash doesn't seem to be related to this mod, it doesn't even mention it anywhere. Its a rendering error, Ancient Spellcraft is not touching the rendering system. Wizardry 4.3 introduced some animations and spells which are tinkering with the rendering system and is currently known to cause crashes like the above, forward this crash to the main mod

**Comment by Gaber373** [comment]
the strange thing is that it worked fine when it was just wizardry
also on client it works just fine

**Comment by WinDanesz** [comment]
Hmm that last one is now different, I'll have a look at it. It still does't mentions the mod but I use AS

**Comment by WinDanesz** [comment]
Fixed in 1.1.1
