### ISSUE TITLE
Super long wizard names

### ISSUE THREAD

**Issue by smoothuk** [WinDanesz/AncientSpellcraft#57]
Since the last update (1.2.2), regular Wizards and Evil Wizards spawn with name shown as 'entity.ancientspellcraft:wizard_as.name' and 'entity.ancientspellcraft:evil_wizard_as.name'.

**Comment by EarthboundRune** [comment]
I am also having this problem

**Comment by WinDanesz** [comment]
Should be fixed in the latest versions
