### ISSUE TITLE
Pocket Dimension completely empty

### ISSUE THREAD

**Issue by Awoo-desu** [WinDanesz/AncientSpellcraft#6]
When entering the pocket dimension using the master-tier sorcery magic of the same name, it sends me to a void which instantly kills me. No blocks, no nothing. Unsure whether this is intentional or not.

Alternate issue that i find funny, but I think it's on IAF's side, ice and fire dragon nests spawn in said dimension. Version 1.1.1, using Electrobobs 4.3.1.

**Comment by WinDanesz** [comment]
Hi, its not intentional, there should be a 11x11 box as the pocket. Is this a server or SSP? Anything related in the logs?

**Comment by l337h4l** [comment]
I have this issue as well on a server, but I think mine is due to player data but I could be wrong.

**Comment by Rockpaw** [comment]
When using the Mod Ice and Fire you need to disable dragon spawns in the pocket dimension in the Ice and Fire config. I had the same issue and disabled dragons spawning in other dimensions and it seemed to fix this.

**Comment by WinDanesz** [comment]
I'll rework the Pocket Dim spell's code as falling in the void due to missing pocket is a common error. Regarding I&F, they should probably add checks to their entities to not just spam them everywhere by default

**Comment by WinDanesz** [comment]
Should be fixed in 1.2.0
