### ISSUE TITLE
Shader effects for EBwizardry spells "slow time" "transience" and "possession" do not work + performance issue with "possession"

### ISSUE THREAD

**Issue by bluejello42** [WinDanesz/AncientSpellcraft#61]
mods used: latest curseforge versions
EBwizardry
Ancient Spellcraft
Lag goggles

issue:
With Ancient Spellcraft installed the spells "slow time" "transience" and "possession" do not display their shaders, and possession cuts the framerate in roughly half. 
The "Sixth Sense" shader works as expected, however.

**Comment by WinDanesz** [comment]
Hello, have you tried to replicate the same issues with just Ebwiz?

**Comment by bluejello42** [comment]
The issue does not happen without ancient spellcraft installed, I made sure to check.

**Comment by tysonwheat123** [comment]
I am having the same issue, whenever I use the possession spell, the effect doesn't work and I lag a crap ton. I have no clue how to fix this and I'd like to have this fixed. 

If there is anything I can do to help you fix this, please let me know and I'll try my best to get you what you need

**Comment by WinDanesz** [comment]
If you can post a lag googles profile data pic, that would help

**Comment by tysonwheat123** [comment]
How do I do that? Sorry , I've never heard of a lag googles profile data pic

**Comment by bluejello42** [comment]
I remembered I had posted a lag goggles FPS profile in a issue on the ebwizardry github (https://github.com/Electroblob77/Wizardry/issues/729)

![138746630-e50b6922-0970-4e2f-aacc-3da8b4f66808](https://user-images.githubusercontent.com/75703767/151852388-c3984cff-1224-4937-b960-5122a44bce91.png)
and the log had a lot of lines of: "Could not find uniform named InSize in the specified shader program." 

I also noticed that only sixth sense had a shader path defined in this mod, as part of astral projection.  wondering if the issue is due to the game trying to find the shader at the wrong location.

**Comment by WinDanesz** [comment]
Fixed by 6e7e4e945
