### ISSUE TITLE
Keeping entity ancientspellcraft:wizard_as that already exists with a random uuid

### ISSUE THREAD

**Issue by DoctorMage** [WinDanesz/AncientSpellcraft#62]
Putting this here so its better kept track of
Modpack:Rad 1.47a
Mod version: AncientSpellcraft-1.12.2-1.2.3
(this also occured in 1.2.2
Issue for an unknown reason an invisible unkillable entity will spawn with this appearing in the logs
[10:01:48] [Server thread/WARN] [net.minecraft.world.WorldServer]: Keeping entity ancientspellcraft:wizard_as that already exists with a random uuid
/kill @e does not work neither any other type of the /kill commands
The current fix is to change the following line to false
# If true, A.S. will alter the wizard entities to inject into their trade list. Disable if you are having issues related to this feature.
        B:"Enable Wizard Entity Changes"=true
Logs before fix
[2021-10-31-5.log](https://github.com/WinDanesz/AncientSpellcraft/files/7448515/2021-10-31-5.log)
https://streamable.com/jrch85
Logs after fix
[latest.log](https://github.com/WinDanesz/AncientSpellcraft/files/7448520/latest.log)
https://streamable.com/n0dw19

**Comment by WinDanesz** [comment]
This shouldn't occur anymore, since the last few versions. That entity was removed from the addon.
