### ISSUE TITLE
Log spam followed by server crash.

### ISSUE THREAD

**Issue by Sereath** [WinDanesz/AncientSpellcraft#63]
There was alot of spam on the server's console with this:

https://gfycat.com/perfectdelayedcrayfish

The very odd thing is that the logs show nothing like that.

latest.log

https://gist.github.com/Aeron216/e97192bf4b3f665b7504764c899fd432

Followed shorty after by a crash:

https://gist.github.com/Aeron216/b9bafeb6bdf9f57b3494de5953721f46

Triggered during a fight between your two types of wizards. It was a 5v5.

I then proceeded to turn this to false

        B:"Enable Wizard Entity Changes"=true

And couldnt trigger the crash again, however Im still getting alot of  very odd console spam:

https://gfycat.com/indeliblecarefuljenny

**Comment by WinDanesz** [comment]
Should be fixed in the latest versions
