### ISSUE TITLE
Candlelight performance issues

### ISSUE THREAD

**Issue by DoctorMage** [WinDanesz/AncientSpellcraft#70]
When used the spell candlelight and moving at high speeds causes the game to have large amounts of lighting updates this can heavily effect fps even when above ground and underground.
also seems to be system dependant.

Regarding discussion on dreams discord for the roguelike dungeons and adventures modpack.

**Comment by WinDanesz** [comment]
I did some changes to these dynamic spells recently, worth a shot with the latest release to see if the performance is now better

**Comment by DoctorMage** [comment]
apologies for the late update tested recently and seems that the spell does not produce any light when moving or standing still

**Comment by WinDanesz** [comment]
Fixed in #96
