### ISSUE TITLE
Spelldagger battlemage crash

### ISSUE THREAD

**Issue by DoctorMage** [WinDanesz/AncientSpellcraft#71]
Mods involved
Ancient Spellcraft 1.2.3
jei_1.12.2-4.16.1.301
ElectroblobsWizardry-4.3.4-MC1.12.2

When having the spell dagger in your inventory if you equip a full set of none elemental battle mage armour your game will crash
with a ticking player the only fix is deleting the item with an nbt editor from your inventory.
https://streamable.com/zh1176

[crash-2022-01-08_00.04.24-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/7831940/crash-2022-01-08_00.04.24-server.txt)
[latest.log](https://github.com/WinDanesz/AncientSpellcraft/files/7831943/latest.log)

**Comment by Zarchyar** [comment]
Encountered the same issue
From the Roguelike Adventures and Dungeons modpack version 1.49 of the pack

On GD Launcher

[latest.log](https://github.com/WinDanesz/AncientSpellcraft/files/7832386/latest.1.log)
[crash-2022-01-07_17.03.34-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/7832385/crash-2022-01-07_17.03.34-server.txt)

Additional crashes on GD Launcher that I don't have the latest.log file for
[crash-2022-01-07_18.11.06-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/7832156/crash-2022-01-07_18.11.06-server.txt)
[crash-2022-01-07_17.35.00-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/7832157/crash-2022-01-07_17.35.00-server.txt)
[crash-2022-01-07_16.58.55-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/7832158/crash-2022-01-07_16.58.55-server.txt)
[crash-2022-01-07_19.06.07-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/7832159/crash-2022-01-07_19.06.07-server.txt)

Multi MC Launcher
[latest.log](https://github.com/WinDanesz/AncientSpellcraft/files/7832162/latest.log)
[crash-2022-01-07_19.28.26-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/7832378/crash-2022-01-07_19.28.26-server.txt)

**Comment by WinDanesz** [comment]
This should be fixed already in the latest versions
