### ISSUE TITLE
3rd Person View being impaired by Ancient Spellcraft 

### ISSUE THREAD

**Issue by Mastarin** [WinDanesz/AncientSpellcraft#73]
Test instance with mods: 
• Ancient Spellcraft version 1.3.1
• EB Wizardry version 4.3.4
• JEI
• Betweenlands version 3.8.1

https://user-images.githubusercontent.com/76500929/152652712-a4a45b24-871b-42b6-8972-4fe9af0ba2f9.mp4

Issue in video is occuring. Prevents players from entering the 3rd person for the Weedwood Rowboat

**Comment by Mastarin** [comment]
Note: Video was performed in a stripped down RAD pack in order to narrow the problem to whichever mods were causing the issue.

**Comment by WinDanesz** [comment]
But the boat is still functional 1st person? I'll fix the issue anyways

**Comment by Mastarin** [comment]
> But the boat is still functional 1st person? I'll fix the issue anyways

No, the boat moves opposite to the direction the player is facing, meaning if the camera is not angled properly, which it cannot be, the boat does not function *properly*.

Functions? Yea, but not properly. Un-useable in it's current state. Thank you tons :)
