### ISSUE TITLE
Game crashes when shooting a bow

### ISSUE THREAD

**Issue by Roy1341** [WinDanesz/AncientSpellcraft#77]
After I installed the newest update. My game crash when I shoot an arrow from Any Bow. I tried with enchantment and 1 without. This is the log, help please.
[crash-2022-04-05_19.47.47-server.txt](https://github.com/WinDanesz/AncientSpellcraft/files/8417810/crash-2022-04-05_19.47.47-server.txt)

**Comment by WinDanesz** [comment]
fixed in v1.4.1
